# Generated by Django 4.1.7 on 2023-04-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='has_exif',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
