# Generated by Django 4.1.7 on 2023-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_accessibleimage_has_exif'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='exif_data',
            field=models.JSONField(default=dict),
        ),
    ]
