# Generated by Django 4.1.8 on 2023-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_accessibleimage_exif_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
