# Generated by Django 4.1.8 on 2023-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_accessibleimage_is_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='labels',
            field=models.JSONField(default=dict),
        ),
    ]
