# Generated by Django 4.1.8 on 2023-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_accessibleimage_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='large_rendition_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='medium_rendition_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='original_rendition_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='thumbnail_rendition_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
