# Generated by Django 4.1.8 on 2023-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_accessibleimage_large_rendition_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibleimage',
            name='large_rendition_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='medium_rendition_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='original_rendition_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibleimage',
            name='thumbnail_rendition_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
