# Generated by Django 4.1.8 on 2023-05-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_accessibleimage_large_rendition_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibleimage',
            name='large_rendition_url',
        ),
        migrations.RemoveField(
            model_name='accessibleimage',
            name='medium_rendition_url',
        ),
        migrations.RemoveField(
            model_name='accessibleimage',
            name='original_rendition_url',
        ),
        migrations.RemoveField(
            model_name='accessibleimage',
            name='thumbnail_rendition_url',
        ),
    ]
