# Generated by Django 4.1.8 on 2023-05-12 05:04

import apps.base.serializers.images
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_content',
            field=wagtail.fields.StreamField([('large_image_grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('images', wagtail.blocks.StreamBlock([('image', apps.base.serializers.images.ApiImageChooserBlock())]))]))], null=True, use_json_field=True),
        ),
    ]
