# Generated by Django 4.1.8 on 2023-06-07 02:40

import apps.base.serializers.images
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_images',
            field=wagtail.fields.StreamField([('image', apps.base.serializers.images.ApiImageChooserBlock(required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
