# Generated by Django 4.1.8 on 2023-06-14 04:09

import apps.base.serializers.images
import apps.base.serializers.pages
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_hero_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_content',
            field=wagtail.fields.StreamField([('call_to_action', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.TextBlock(required=False)), ('image', apps.base.serializers.images.ApiImageChooserBlock()), ('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', apps.base.serializers.pages.ApiPageChooserBlock(icon='home', required=False)), ('url', wagtail.blocks.URLBlock(icon='link', required=False))], max_num=1, required=True))]))])), ('filmstrip_images', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('images', wagtail.blocks.StreamBlock([('image', apps.base.serializers.images.ApiImageChooserBlock())]))])), ('image_grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('grid_size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('images', wagtail.blocks.StreamBlock([('image', apps.base.serializers.images.ApiImageChooserBlock())]))]))], null=True, use_json_field=True),
        ),
    ]
