# Generated by Django 4.1.7 on 2023-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='collections',
            field=models.CharField(choices=[(1, 'Root'), (2, 'Cancun 2022')], max_length=255, null=True),
        ),
    ]
