# Generated by Django 4.1.7 on 2023-02-28 01:38

import apps.base.serializers
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallerypage_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='collection',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='images',
            field=wagtail.fields.StreamField([('image', apps.base.serializers.ApiImageChooserBlock())], null=True, use_json_field=None),
        ),
    ]
