# Generated by Django 4.1.8 on 2023-04-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_gallerypage_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='images',
        ),
    ]
