# Generated by Django 4.1.8 on 2023-04-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('gallery', '0010_remove_gallerypage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='collection',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.collection'),
        ),
    ]
