# Generated by Django 4.1.8 on 2023-04-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_accessibleimage_exif_data'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('gallery', '0011_remove_gallerypage_collection_gallerypage_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='collection',
            new_name='image_collection',
        ),
        migrations.CreateModel(
            name='AlbumsLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('preview_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.accessibleimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
