# Generated by Django 4.1.8 on 2023-05-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_rename_collection_gallerypage_image_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='grid_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='large', max_length=10),
        ),
    ]
