# Generated by Django 4.1.8 on 2023-05-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_accessibleimage_large_rendition_url_and_more'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('gallery', '0013_gallerypage_grid_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryPage',
            new_name='AlbumDetailPage',
        ),
    ]
