# Generated by Django 4.1.8 on 2023-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_rename_gallerypage_albumdetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdetailpage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Check this box if the album is public.'),
        ),
    ]
