# Generated by Django 4.1.8 on 2023-06-01 02:57

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_albumdetailpage_delete_gallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdetailpage',
            name='hero_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=True))], null=True, use_json_field=None),
        ),
    ]
