# Generated by Django 4.1.8 on 2023-06-01 03:25

import apps.base.serializers.images
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_albumdetailpage_hero_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetailpage',
            name='hero_images',
            field=wagtail.fields.StreamField([('image', apps.base.serializers.images.ApiImageChooserBlock(required=True))], null=True, use_json_field=None),
        ),
    ]
