# Generated by Django 4.1.8 on 2023-06-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_accessibleimage_large_rendition_url_and_more'),
        ('gallery', '0020_alter_albumdetailpage_hero_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumdetailpage',
            name='hero_images',
        ),
        migrations.AddField(
            model_name='albumdetailpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.accessibleimage'),
        ),
    ]
