# Generated by Django 4.1.8 on 2023-06-01 03:42

import apps.base.serializers.images
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_remove_albumdetailpage_hero_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumdetailpage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='albumdetailpage',
            name='hero_images',
            field=wagtail.fields.StreamField([('image', apps.base.serializers.images.ApiImageChooserBlock(required=True))], null=True, use_json_field=None),
        ),
    ]
